os: linux
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=armkom/rso-content-model-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: Ew+mscEpgkAptXYg+rvMr0GxZQkXnQt43H5VdJdgcWzAVKfRbHbuC16YvuofwbgIblgP+OBjNVvDSlSZrqBVDPvVakTNfM7d3/QJJxN7h4N1qhMvm0ZdicYUBuk514pV8NiB4HJge/MFaRE4qV2LI86wqII/nWDXgV9s69GyffAM0Ww+6EhxEIvopsrMI/wpq66qrzEhQ3HEupVqBSRCOIkgs4Wa6SXBCFsypGfq7tsnDlP+n1Jy6nLmK2/lXLP7TygYJktXputwUSR53ukgsLz1SVY35DV3UG6RLdD4gUKurqRuuESdruqqcuDSUB5tXlZxbOjvMwYIQvovF9D2nMjJTgpVNwVpLezQ8sdYfrs4RxW/0N6Jn1Qh3NvhHaABw6t0qSe17MfOrL/0OQ5XVQqCkSq8pKpNF1LHeAZ1fNGtDjwHU5Ty+43KZDCNwUj4y25dHSgYeWNyrp9C9kkpxbXNw7gkRjYUqkpoa3CTC5pYfotvwtLeqO1WZzPcrI0HGXJcDdJO9Sie16PpEGQ9BLjNkRGHvaD28vl5SOkK28XboFgeQq1EZAJEhHm+gMlWt8TrV6fX5FnbEpiiGrKqFCHRCoEOyvMTwZ9FHDBv5cdu09HjB3O4Qs9h/lB8eic9B1l+2lxSkguIX7LIGiMi5tV+hiWFL3hmLB5s5Yj80vY=
  - secure: ijs4FZ9+SSocp5FfQ03e6+/P5JQzTw1WEpmkaMZFSQuVpkogn8NA8pZxSBVRiIHqqTwoz1llPidHmRH3RlOiafd/4TIl2X2XKE4dNid7m06sRCPcaHYt4qX0dS7p4iHX7Z00dGEchlEWlEYlwn9SlgiE5syGjsUDnUtM8Yh2OEgo5V9dbJ42o5wgbb74NIUnEVKu8Xyd3vsEq2C+mjHXc41TcURSkElqYuWjXD2lkq6ME3JjJO1Urf2lWI3JtSK6qVldnChpUGd2qIyMAj0p+H6RDvNGoFkIN/BY33uPGctnniWX7GUo39QGIG1rwuxrFYQ2xXsBAmHx4oMmRVgZqBk1APVgukF/lpl+0RMgM4VSHW1IdXuYtMsBuPXTrgVsAUOPqknH40yzfD7WIJ6E+kdrHCuanZrZ9u5cV0+lj92D8LGo6XBSfQMAAoVkeqc4fPlkxM8TE4Xg7lVynEEvAekRMO99/j62BeO44DB8+GPYl9CDNwXrQ5n2p3iaWYk1RAHCvTvVYXM4R5Y/8ESMTM5ad7fjILikiO2BPSxw3yeGXooXzruANnLJK5p3qSzxGoVDbUQD2ke+Dll+ZNvlfIA0oF60ndg1kluf1v+qsmsI1Q6wm4z/8aBM0XtYckykS5Lc0fePx4zdUzAnP4AlbFIrBzssdwQRyJJKg6b2kt8=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"
