os: linux
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=armkom/rso-content-model-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: KBD9hyq8bDMg8MHjcPq71FrzvoG5q4/5lk63r0HB1OfqmkQkBRovODP2YZwMW9JS3FIpw4FGb2WjgUqUFoWuveNtbzTZF2W17DTpOHjcbR17yKbj8krmaB1VB9b9LWJDJ6nLgpj6mbgdp2GCT1QksUobATn0S26den/bE7qdLFgKxTFsA6LCPh7ujYod3kGfgM2yRT6B1FVz8eOFnzBU3nqpB1XXoU+WLg3xR1ihaKLKd1U2qgyBtuUNpHeClEdJfR5tcoCQbLoVE+C0/kir1KnDBUbKZMcerC8y8jNtxKdgxu4w1kK9qYguRGR7YNaz8aLroZW9DVKDRP9MaWphuD4DR7ImF+uRQzHnzu6CwARJxVI35YPQQOOHfftBsGFy7T7DpqafT7DP6DmB6b9KUzt41uKwEtuq6sIZVcRtzV5vZqf0AzqGoRhHXtAD0UR6ujyyC9xCfuP/5tHk3WyrxIkscf/luo84wLYjDuJbU9YJO6h4VDZFqX4yJLR30ps0AWow906peTvlo5DkypGGzrgBXsSnzFB2u4yTfsYRCEb80VEhQrVEPXRBcPUrbGCtusP5py+KB7KqNVhZmZpoIfFWgDXsifA0O1LfeJUVkEz2Z505pZ+94lt0/XqBeSghIbOf/QXcN8G37sDFNuWv3GV555JVDmswnJIVeX3l8Pw=
  - secure: iAJrtI1xPMAN299wa70Ghz73D7f5eomTzHZguox8DhcMhcZebSeuH8QR3EKn8FVbvGXCSkc6n5TZbDwMfrqnTZElKR3SZpOD3BWIZ6Ozg9Ud4piZp5/Y8SyyWHNehRzancXkO/SdUWzMsdZX1fzRj/bQZMmdU9KQxcpIUbnOw8dAfchBPdVJiWnjN0eqDXV6wbHVgaYU0U+w5/VVl9xImkqDBnnWcdHNl8vBwwZa8c/j50BeoGqBzMxnyhqbTNgTUab5CBfXOAVzdOefoLho9ZQyF70u/8NKQqAI9OxDeAvoXRRdN2BpmxOtg1fHBgIg4Ty++wh5Z0Fyu5UnfQWxdIrsL31RG26s09v10jgAy/o58mtWqlQD6m35HaZoKoUHH51YHtImVFmEukctu9AzZFmSh7hBbMcnIZMwh9cXWWybncAc1PdRcz4uOWPdKSJkLqTjSIlAhPBfdP43Tz2rmXW4gwpKckDyl++zv9dQxtBPb7qLYH1PBZ/vu8O8F490AdAAgCPCbOAZ/ali+d9+FKAB0lcJ9pRJ14/BxJyxaKLEC7gKAbfv+AoHzOayOa4y6/XAkREDSi64MexSBHDj04sUe9bXCbPscFbLkENFCNGZbxfHGMfEs8RQkafxCs0LNLSO1W4TO3GJqCz48PSETuKkZp89kd2nxuA8mDAxquY=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
