os: linux
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=armkom/rso-content-model-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: aaUuUvXjhJ9UBDW+lUeXP0kMYUsOBPfLteRsy5erRBtymTP6B8f7BVOtRJU5QQBMsp0+0KudGz8iUaRB5MllCj4nbIjK5nHHnocG41upImXoJeaMLl2KslWFrR3WlnkdfJC2Pv40zxOof2nrOEQgNWYL0gkbXbcJCEa26LYMh1WaQ6jd8C1K2Z2HcJ+jyWpMMG4LiKeKbw6GKiwGMzYxSk4Mn27c4BM1JucMPz/BsVshvicY2ZJm/cwMU0zKjmejZKt0EtEVhEcjLddLXk1DFuixYRs/q7gKiFH5e4Z3OvLvT04hXqkRWoJCx98IeFe3q2b/x0q1kVW/APy246FEtvdbkAQxN5hgbVdFB4bwMPuHwbJOkEqQmiF/QSSb6vJ2lyyLLmyBHC4rR5MqA2BRzKyluovXAaYLS0f6iLMN2D0R0IsD57mBZnDzIAtiW/xgT/l++cgOm+W8HLerQtfOQdkhAFc1BqTTHc34ARqNFBEJp9JlcZi/IFCsQ7xwmX1Sci7W9hgvthWczy0CV3B4LDy9ATNS/w5I6OqpLubSds6Zd6CEqBHdQv+/zpKTnvjxFyhNRWz4UF2/LIvzTQCD6rJWj1sPculuJlveLy9Wo9+K2g4Te1pBg0iFZ0N+cSD50vGUv8ad5w4cam5n7hMslYtfXAYEn8pMnix7batADLc=
  - secure: R8QmHmref43DXWMYOe0D8jeH1TtTH/Jf2b3EvPI/S+siy3PCQun3kJXPryGM44N6sQ5h+JuBO5cNuOobrS4bQ0eF2VJ3jlcWEOpDsQg0KcJLavCZ3cvH5CDhfZOgH0IO5Ju+KownRexRGWyYWsAwn5ZRO8vhFBR2n+rXs9PkzhI/Vq8ZEvbXteu+C34o4ZMMh8dpIRi3Pm8XlF3VBIYrC0i6C4idAg9vgZsq+rActNVR0GN8Ngu+1TbLXMtm++IcmqmXzct7PRluInkZI8WbQW//ZYdk3sDBvjqhtXW4lQEsC7kWbvvj1tlabN9AN3iJCBh424s7+GaxR1seHZ6NhXCwc7DfjIEf1LsQH5k+sX/mt7Qg9t/7rkrNnY7MS0YhcLNWU/twbfwz8zyUe9Usc+P/Cp6w+BrAnLnactqjCJ5+gw9nSKx+o5ZTIDioMV8UNjPY8EHkYeUPNgCfleEIDjvQGriA5fynreV9g0qVJfMYNroLhc9aiFACk70EzpdY8A/evIzcA6eU13POTFRitenqRoXLxCIlF8qOKDhfpvbjwrDNASjyl1gg4dcGVp3kxQZWltfTXHSScn4RpdMJRKi7b73JzXouK8nCEla2xoYDA8/Dr3PBkS5XCCmD/Z5UKUnWIl4gFv0E08VS48LzPB6oXWIz32HKGI103IEZpLI=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
