os: linux
services:
- docker
language: java
dist: bionic
jdk:
- openjdk14
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_IMAGE=armkom/rso-content-model-api:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER
  - secure: CXu33BVXxiim3cGMDTnR5X8pdyWOLJhjp/Q4euq+/cr/sFsxWhK4IiZgSfXmxf9I94kIDfa6paDbxPsr5pXIPc9G8Uwu8iXmm3muJcVWUOQY+WrL/jalyItWfu79oV5mQk6eFFQ1zkwzUR9Raj22UAyoBVMUxIs15l3zlwJyPYRM/fkXE7uv0OoglxWPHiy1rVHDh+oFce25Dba3O+IniMBxoRVAsNaHvoIG2D91uOG8W8au8QgyrsMlRVE/askf68EuV/nJAA2vMx4DKwPO+Rra3MKuZLIzUUNZP90T6vrlyUqFnx19Q1AkpBxkx4Br2MYsQTn+Op9bOa4qkaAZBSnJGILc587rZTUXMIAWOsGH5o9a7NIDR6//y9z/v3HOZHcuIHkz/ES5z/VIfco9+oWx81NWB+1vbweIheyQsqshpPJj7gwmUTMuYXJshftrNJMuG1g6y5MPtXTKwSI+dtdS/RecpvqSBh+roV7eZsxCM5yJZAXtjrcstfebKVse4IFLbIhii3yLgk+0iBcoAgJpNdOJhE14UK80JXqxoKB786uet6gw6Jh1tfocbptHYcSh4wN9AqExFNlEntaOdp4Y1oxR4xw0EDDY59OxrJYdGTSogJA3Npp98huyyJuePBJkihqf3ynDS1CJtaovg/bg9VCTqTrnDwHl8RoNbyk=
  - secure: VdmAYXpmjjD8EDPD7UklRV4huqFf8IskN9SfblY+DkI6uVZELSf+XaMNA4CnkFVSx/rdH0X05SHQcIL9GdUWJWFIoN1r7MVoFO8z+3y4OCCQCDdK1qVhtC9JyQZcoxwBeihYADK0oQ7Cuj0ZarKbvMBz5fxy5uDwWgAUTEDqlk0539y3K5CclhP30IA+2Yfxz3feeoPKGW87J3HJCdqrbODghdLAxHeVwR33k4Ckw2k0m7w4nABnRELZAQMSgqSMQ7CBnMl/3W84MuOP6wyY//R4262i+A+AUMhPT8JOszffjQqVsiiNw75AkFQOw5owqf1z4IuJivQBuSDeZMZ+oRK9yozPBJ4RGMuywieHfn2BttiKVfQnpeva2/+x4dw/wzk9EN9dSZAL0js0Cjoxtvi+tAeioZDMgvZklimTZ+VzMzMTo2TsriNCCbVAqcHNcHzFDmGvE1q2c5S+N/Kg4XzZ54Uz7kwqorRUdQKYeTiIjjaaP7WtGWqn4oqMLY1pzQ22SRMetlwU/ncpxUH5E3ctoRi6nbM7qezZwTx2PsdnCffrnX3FZ5ds4d9JtGIM0FnTbukYwZs/qJ9O8M0fVnEH2Gi9mzUboV6CLSfOUQFWSpYmqUKeGe5R/JNfB//WZdXFYI30tiSm+z6oVRnl6v/FVMtMKGfSDuLWyJh3hN0=
script:
- mvn clean package -U
- docker build -t "$DOCKER_IMAGE" .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push "$DOCKER_IMAGE"
